export const formSchema = {
  title: "Employee Onboarding",
  description: "Onboarding form for new employees.",
  fields: [
    {
      name: "fullName",
      label: "Full Name",
      type: "text",
      placeholder: "Enter full name",
      required: true,
      validation: { minLength: 3, maxLength: 100 },
    },
    {
      name: "email",
      label: "Email",
      type: "text",
      placeholder: "name@company.com",
      required: true,
      validation: {
        regex: "^[^\\s@]+@[^\\s@]+\\.[^\\s@]+$",
      },
    },
    {
      name: "age",
      label: "Age",
      type: "number",
      placeholder: "Enter age",
      required: false,
      validation: { min: 18, max: 65 },
    },
    {
      name: "department",
      label: "Department",
      type: "select",
      placeholder: "Select department",
      required: true,
      options: [
        { label: "Engineering", value: "engineering" },
        { label: "HR", value: "hr" },
        { label: "Finance", value: "finance" },
      ],
    },
    {
      name: "skills",
      label: "Skills",
      type: "multi-select",
      placeholder: "Select skills",
      required: false,
      options: [
        { label: "JavaScript", value: "js" },
        { label: "React", value: "react" },
        { label: "Node.js", value: "node" },
      ],
      validation: { minSelected: 1, maxSelected: 5 },
    },
    {
      name: "joiningDate",
      label: "Joining Date",
      type: "date",
      placeholder: "Select joining date",
      required: true,
      validation: { minDate: "2020-01-01" },
    },
    {
      name: "notes",
      label: "Notes",
      type: "textarea",
      placeholder: "Additional information",
      required: false,
      validation: { maxLength: 500 },
    },
    {
      name: "isRemote",
      label: "Remote Employee",
      type: "switch",
      required: false,
    },
  ],
};
